name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 触发分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm cache clean --force
      - run: npm install
      - run: npm run build -- --platform github
      - name: Check build output
        run: |
          echo "构建后的 index.html:"
          cat dist/index.html
          echo "资源路径检查:"
          grep -i "src=\"/metro-app/" dist/index.html || echo "未找到匹配的资源路径！"
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # 构建输出目录
